publishDir = "docs"
baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-future-imperfect"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "https://matthewhuebsch.github.io"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/matthewhuebsch"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/matthuebsch"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
[params.intro]
    header    = "Signal to Noise"
    paragraph = "Mass spectrometry. Bioinformatics. Algorithms. Markets. Data visualization. R."
    about     = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."

[params.intro.pic]
    src       = "/images/logo.png"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = true
    width     = 60

